### ISSUE TITLE
Help needed for modularizing for Java 11 ++

### ISSUE THREAD

**Issue by goxr3plus** [goxr3plus/XR3Player#10]
Hello my dear friends :) 

I need immediate help of modularizing XR3Player for Java 11 and above , i am still learning and it needs a good effort :) 

Thank anyone for helping :) 

If you have some free time :) 
@Valkryst

**Comment by HelgeStenstrom** [comment]
I made a small test project in Java11. All it does, is to import some stuff that is also imported by XR3Player. So far I'm mostly confused.

https://github.com/HelgeStenstrom/xr3UsageExamples

The project is created in IntelliJ IDEA as a Maven project with JDK11.
The directory structure is as it is created by the IDE. We have src/main/java and src/test/java. 

There is one module-info.java file. It's located in src/main/java.

Files inside src/test/java doesn't care about the contents of module-info.java.
Files inside src/main/java do care. The "requires" of the file determines what the java class files see. Having junit modules listed doesn't seem to be meaningful, since the test hierarchy doesn't care. But we can't have a separate module file in the src/test/java hierarchy: it's not permitted.

So far, I have added dependencies to jaudiotagger, in Maven and as import statements.
I had no luck with https://github.com/goxr3plus/jaudiotagger; with it I couldn't write any "requires" that worked. What module name to write is a guesswork, but the IDE helps with alternatives.
It worked better with 

```xml
        <dependency>
            <groupId>net.jthink</groupId>
            <artifactId>jaudiotagger</artifactId>
            <version>2.2.3</version>
        </dependency>
```

**Comment by HelgeStenstrom** [comment]
guided by https://bitbucket.org/ijabz/jaudiotagger

**Comment by goxr3plus** [comment]
Hey Hey i havr created my own JAudioTagger, chrck the dependencies, i released my own version its there on the dependencies.

XR3Player is a little bit complex i admit, give me some time to fully understand your comment

**Comment by HelgeStenstrom** [comment]
The current purpose of https://github.com/HelgeStenstrom/xr3UsageExamples is not to investigate the business logic of anything; it's to learn how external components can be used in a Java 11 context. 
There is a difference between your jaudiotagger and the original one in that regard.

**Comment by goxr3plus** [comment]
This seems worth reading: https://blog.codefx.org/java/java-11-migration-guide/#Preparing-Your-Migration
I've just started reading it.

I have put this link here for me to remember .

**Comment by goxr3plus** [comment]
Changed all problematic dependencies starting with `V` to follow `X.X.X` release pattern .

**Comment by goxr3plus** [comment]
Closing this as i think it's done :)
