### ISSUE TITLE
SonarLint plugin

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#50]
IntelliJ has a plugin named SonarLint, available for Eclipse too.
It finds a lot of code issues, and comes with good recommendations.
At my workplace, the setup is such that we cannot merge new changes with the master, unless they are "Sonar clean".

SonarLint is an IDE extension that helps you detect and fix quality issues as you write code. Like a spell checker, SonarLint squiggles flaws so they can be fixed before committing code. You can get it directly from the IntelliJ IDEA Plugin Repository, and it will then detect new bugs and quality issues as you code (Java, Kotlin, Ruby, JavaScript, PHP and Python).
If your project is analyzed on SonarQube or on SonarCloud, SonarLint can connect to the server to retrieve the appropriate quality profiles and settings for that project. Java 8 is required to run SonarLint.

More info available at https://www.sonarsource.com/

**Comment by goxr3plus** [comment]
Yes i have been using it for the past two years with Eclipse, actually IntelliJ provides pretty good recommendations so i disabled it brcause it makes the IDE very slow because it does and analysis on every save :)


Actually if this is a recommendation i thank you very much. We don't need to configure anything for it in XR3PALAYER, you can install SonarLint and use it locally in your pc :)

**Comment by HelgeStenstrom** [comment]
I haven't found that it slows down my computer. But if it does, one way to use it is to enable it for a session, analyze some files, and then disable it again. I find that the recommendations that Sonar gives are usually good. And as you say, there is no connection with the current project (XR3Player or whatever), it's just a plugin in the IDE.

**Comment by goxr3plus** [comment]
Yes of course i understand :)
