### ISSUE TITLE
Move on Java 13

### ISSUE THREAD

**Issue by goxr3plus** [goxr3plus/XR3Player#60]
I need some help on passing to Java 13 , i don't think is hard at all .

It's just i found this site => https://adoptopenjdk.net/index.html?variant=openjdk13&jvmVariant=openj9

But how exactly openjdk13 works , like i will bundle it with XR3Player , but it will work on all windows machines like Oracle is used too :) ?

Very excited for the new features Java 13 has.

@HelgeStenstrom

**Comment by HelgeStenstrom** [comment]
Why do you want Java 13?

**Comment by goxr3plus** [comment]
I like the latest :) Never to be behind and every new version brings bug fixes and new features .

**Comment by DropSnorz** [comment]
Hi @goxr3plus  !
I've just seen this issue flagged with _help wanted_, so i will share my thoughts here. I'm maintaining [OwlPlug](https://github.com/DropSnorz/OwlPlug) a Java 9 / Jfoenix app and i've also planned a Java migration. In my case i will wait Java 14, the next LTS version mainly because i need the [jpackage ](https://jdk.java.net/jpackage/) tool.  (btw it still a _Proposed to Target [14]_ feature)


There seems to have a lot of [issues](https://github.com/jfoenixadmin/JFoenix/issues?q=is%3Aissue+is%3Aopen+label%3A%22JDK+12%22) flagged _JDK12_ on Jfoenix repo. I don't know Jfoenix's maintainer plans regarding Java and OpenJFX 14 but i think some efforts will be needed on this side. 

Let me know il you want to go with Java 14, i think we can share efforts and feedbacks. 🙂

**Comment by goxr3plus** [comment]
You have an amazing app right there i had a loook right now :). Of course i
want to go to Java 14, every time Java updates i am going to the latest
version :)

Let's be in contact for collaboration between our projects :)

Very happy that you send me this message.

**Comment by HelgeStenstrom** [comment]
Time to close this ticket now?
