### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by leonardoderoy** [goxr3plus/XR3Player#7]
Hello! @goxr3plus

I'm a graphic designer and I like to support your project because I believe a good logo that reflects your project at its best can help the project publicity and trustability, also i'm an open source enthusiast. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Leonardo Deroy

Graphic Designer

**Comment by goxr3plus** [comment]
Hi my friend ♥, of course i would like your support, can you make a logo similar to the current one but more modern, i need a diamond inside it. Let me see your proposals :)

**Comment by leonardoderoy** [comment]
hi @goxr3plus  Of course, if I am already uploading the proposal

**Comment by goxr3plus** [comment]
Can't see any image?..... :)

**Comment by goxr3plus** [comment]
Very beautiful!! I like a lot image 5. What about a combination of 5 and the letters of 2 inside the circle ;). I would love that. The letters and the big diamond all in the circle :)

**Comment by goxr3plus** [comment]
Actually combination of 5 and 6.

**Comment by leonardoderoy** [comment]
here is the modification if it is to your liking I can do the pull requests
![image](https://user-images.githubusercontent.com/40496274/42255415-99e1a318-7f19-11e8-902c-4fbbed58b0ca.png)

**Comment by goxr3plus** [comment]
This is very very nice, one final step, i want the letters to be inside the
circle too let's say, XR3 on the left bottom corner of diamond ( with a 45
degrees angle) and Player on the bottom right corner of the diamond with a
( 45 degrees angle looking up diagoniallly). I think that will be the
perfect final icon.


That's because imagine if the background color of user is black, letters
XR3Player will be completely invisible as they are now....


Much love ♥

**Comment by goxr3plus** [comment]
Just to check it out how it looks, but i really find very beautiful thr circle with diamond you are suggesting here.

Remember i will need icons (. png and. ico) of  256*256, 64*64, 32*32 proportions.

That's it :)

**Comment by goxr3plus** [comment]
Haven't heard from you in long time ... so i will close this issue ... feel free to reopen.
